.Dd $Mdocdate: November 16 2014 $
.Dt KDATA_MIN 3
.Os
.Sh NAME
.Nm kdata_min
.Nd find minimum y-point in a data source
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft ssize_t
.Fo kdata_min
.Fa "const struct kdata *data"
.Fa "struct kpair *kp"
.Fc
.Sh DESCRIPTION
The
.Nm
function finds the minimum point in a data source, filling in
.Fa kp
if it is not
.Dv NULL .
The minimum point is the first minimum: thus, if multiple minima exist
of the same value, the first will be returned.
.Sh RETURN VALUES
If the data source has zero entries,
.Nm
returns -1.
Otherwise, it returns the index of the minimum.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kdata_max 3 ,
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
