.Dd $Mdocdate: January 30 2015 $
.Dt KDATA_VECTOR_ADD 3
.Os
.Sh NAME
.Nm kdata_vector_append
.Nd append data to a vector data source
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft int
.Fo kdata_vector_append
.Fa "struct kdata *data"
.Fa "double x"
.Fa "double y"
.Fc
.Sh DESCRIPTION
The
.Nm
function invokes
.Xr kdata_set 3
with the point values
.Fa x
and
.Fa y
after (possibly) growing a vector data source allocated with
.Xr kdata_vector_alloc 3 .
.Sh RETURN VALUES
.Nm
returns 0 if the vector reallocation failed, the data source was not
created with
.Xr kdata_vector_alloc 3 ,
or if
.Xr kdata_set 3
fails.
Otherwise it returns non-zero.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kdata_set 3 ,
.Xr kdata_vector_alloc 3 ,
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
