.Dd $Mdocdate: February 7 2015 $
.Dt KDATA_GET 3
.Os
.Sh NAME
.Nm kdata_get
.Nd get points in a data set
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft int
.Fo kdata_get
.Fa "const struct kdata *data"
.Fa "size_t pos"
.Fa "struct kpair *kp"
.Fc
.Sh DESCRIPTION
The
.Nm
function loads the
.Fa kp
pair object with the data at absolute position
.Fa pos
of data source
.Fa data .
.Sh RETURN VALUES
.Nm
returns 0 if the position
.Fa pos
is not within the allocated number of pairs, else it returns non-zero.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
