.Dd $Mdocdate: November 15 2014 $
.Dt KDATACFG_DEFAULTS 3
.Os
.Sh NAME
.Nm kdatacfg_defaults
.Nd set default values for plot data
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft void
.Fo kdatacfg_defaults
.Fa "struct kdatacfg *cfg"
.Fc
.Sh DESCRIPTION
The
.Nm
function sets the default values used internally on a
.Vt "struct kdatacfg" .
.\" .Sh RETURN VALUES
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
