.Dd $Mdocdate: January 25 2015 $
.Dt KDATA_BUCKET_ADD 3
.Os
.Sh NAME
.Nm kdata_bucket_add
.Nm kdata_bucket_set
.Nd modify bucket data values
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft int
.Fo kdata_bucket_add
.Fa "struct kdata *d"
.Fa "size_t bucket"
.Fa "double y"
.Fc
.Ft int
.Fo kdata_bucket_set
.Fa "struct kdata *d"
.Fa "size_t bucket"
.Fa "size_t x"
.Fa "double y"
.Fc
.Sh DESCRIPTION
The
.Nm kdata_bucket_add
and
.Nm kdata_bucket_set
functions add or set the
.Fa x
and
.Fa y
values
.Pq which are not checked for any restrictions
to the bucket index
.Fa bucket
within the range provided to
.Xr kdata_bucket_alloc 3 .
.Sh RETURN VALUES
.Nm kdata_bucket_add
and
.Nm kdata_bucket_set
return 0 if the
.Fa bucket
is outside of the bucket range,
a dependant modification failed, or
the source was not created with
.Xr kdata_bucket_alloc 3 ;
otherwise it returns non-zero.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kdata_bucket_alloc 3 ,
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
