.Dd $Mdocdate: January 16 2015 $
.Dt KDATA_BUCKET_ALLOC 3
.Os
.Sh NAME
.Nm kdata_bucket_alloc
.Nd allocate bucket data for plotting
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft "struct kdata *"
.Fo kdata_bucket_alloc
.Fa "size_t rmin"
.Fa "size_t rmax"
.Fc
.Sh DESCRIPTION
The
.Nm kdata_bucket_alloc
function creates a reference-counted data sources for
.Xr kplot 3 ,
initially with x-values set to the pair index starting at
.Fa rmin
and y-values to zero.
It is similar to
.Xr kdata_array_alloc 3
except it uses a bucket data model: each integer within the range
.Fa rmin
(inclusive) to
.Fa rmax
(non-inclusive) corresponds to a specific bucket.
Bucket values are modified with
.Xr kdata_bucket_add 3
and
.Xr kdata_bucket_set 3 .
.Sh RETURN VALUES
.Nm
returns
.Dv NULL
if memory allocation failed.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kdata_array_alloc 3 ,
.Xr kdata_bucket_add 3 ,
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
