.Dd $Mdocdate: January 29 2015 $
.Dt KDATA_PMFSTDDEV 3
.Os
.Sh NAME
.Nm kdata_pmfstddev
.Nd compute probability mass function standard deviation of data
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft double
.Fo kdata_pmfstddev
.Fa "const struct kdata *data"
.Fc
.Sh DESCRIPTION
The
.Nm kdata_pmfstddev
function compute the standard deviation (i.e., the square root of
.Xr kdata_pmfvar 3 )
of its data as if it were a probability mass function.
.Sh RETURN VALUES
If the data source has zero entries or the sum of the y values is 0.0,
.Nm kdata_pmfstddev
returns 0.0.
Otherwise, it returns the standard deviation.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kdata_pmfmean 3 ,
.Xr kdata_pmfvar 3 ,
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
