.Dd $Mdocdate: November 18 2014 $
.Dt KPLOT_DRAW 3
.Os
.Sh NAME
.Nm kplot_draw
.Nd plot data on Cairo context
.Sh LIBRARY
.Lb libkplot
.Sh SYNOPSIS
.In cairo.h
.In kplot.h
.Ft void
.Fo kplot_draw
.Fa "const struct kplot *p"
.Fa double w
.Fa double h
.Fa "cairo_t *cr"
.Fa "const struct kplotcfg *cfg"
.Fc
.Sh DESCRIPTION
The
.Nm
function draws all data sources onto a Cairo context
.Fa cr
of height
.Fa h
and width
.Fa w .
It performs all the necessary range and domain checks to fit all data
sources into the image.
.Pq If no points are specified, the domain and range are zero.
The image is laid out as described in the Drawing Model section of
.Xr kplot 3 .
The options provided via the
.Fa cfg
object are as follows:
.Bl -tag -width Ds
.It Va margin
Bitfield of which margins to draw:
.Dv MARGIN_LEFT ,
.Dv MARGIN_RIGHT ,
.Dv MARGIN_TOP ,
.Dv MARGIN_BOTTOM ,
or
.Dv MARGIN_ALL .
.It Va marginsz
The width of the margin in user-space Cairo coordinates.
These are clamped to be non-negative.
The margin is the space between the image boundary and the longest (or
tallest) label edge, or if no label is specified on any face, the plot
area.
.It Va ticlabel
Bitfield of which labels to draw:
.Dv TICLABEL_LEFT ,
.Dv TICLABEL_RIGHT ,
.Dv TICLABEL_TOP ,
or
.Dv TICLABEL_BOTTOM.
.It Va ticlabelclr
The colour index of the label text.
.It Va xlabelpad
Space between horizontal (x-axis) labels and the plot area.
Specifically, between the edge of the longest label along any face and
the plot area.
.It Va xlabelpad
See
.Va xlabelpad .
.It Va xticlabelrot
Rotation of horizontal (x-axis) labels (in radians) clamped to 90 degrees.
Rotation is clockwise.
.It Va xticlabelfmt
This function may be user-defined for formatting the horizontal x-axis
label as a UTF-8 string limited to 128 bytes (including nil terminator).
It accepts three arguments: the value to format, the string buffer in
which to format, and the size of the buffer.
The default is to use
.Xr snprintf 3
with the
.Li %g
format string.
.It Va yticlabelfmt
See
.Va xticlabelfmt .
.It Va border
Bitfield of which borders to draw:
.Dv BORDER_LEFT ,
.Dv BORDER_RIGHT ,
.Dv BORDER_TOP ,
.Dv BORDER_BOTTOM ,
or
.Dv BORDER_ALL .
.It Va borderclr
The colour index of the border.
.It Va bordersz
The Cairo pen width of the border.
Note that this is the diameter of the pen, extending to either side of
the border line.
.It Va clrs
Array of RGBA colours for the colour index.
Each RGBA value is clamped to the unit interval.
If no colours are specified, opaque black is used.
.It Va clrsz
The number of colours in clrs.
Colour indices (e.g.,
.Va borderclr )
index into the
.Va clrs
array modulo this value.
.It Va xtics
The number of tics (and thus labels) to draw along the horizontal
x-axis.
The border condition (one tic) is drawn in the centre.
.It Va ytics
See
.Va xtics .
.It Va tic
Bitfield of which tics to draw:
.Dv TIC_LEFT_IN ,
.Dv TIC_RIGHT_IN ,
.Dv TIC_TOP_IN ,
.Dv TIC_BOTTOM_IN ,
.Dv TIC_LEFT_OUT ,
.Dv TIC_RIGHT_OUT ,
.Dv TIC_TOP_OUT ,
or
.Dv TIC_BOTTOM_OUT .
.It Va ticlen
The length of the tic-mark in any direction.
.It Va ticclr
The tic colour index.
.It Va ticsz
The pen width for drawing tics.
.El
.It Va grid
.Dv GRID_X ,
.Dv GRID_Y ,
or
.Dv GRID_ALL .
.It Va gridsz
The width of grid lines.
.It Va gridclr
The colour index of grid lines.
.Pp
If
.Dv NULL
is passed as a configuration, reasonable defaults are used.
.\" .Sh RETURN VALUES
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kplot 3
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
